[package]
authors = ["Lucas Pickering <lucas@lucaspickering.me>"]
description = "Persist arbitrary program state quickly and easily"
edition = "2021"
license = "MIT"
name = "persisted"
repository = "https://github.com/LucasPickering/persisted"
rust-version = "1.60.0"
version = "0.0.1"

[workspace]
members = ["persisted_derive"]

[dependencies]
derive_more = {version = "1.0.0-beta.6", default-features = false, features = ["debug", "display", "deref", "deref_mut"]}
persisted_derive = {path = "./persisted_derive", optional = true}
serde = {version = "1", default-features = false, features = ["derive"], optional = true}

[dev-dependencies]
rusqlite = {version = "0.31.0", default-features = false, features = ["bundled"]}
serde_json = "1.0.117"

[features]
default = ["derive"]
derive = ["dep:persisted_derive"]
serde = ["dep:serde"]
